var Id = 5464654;
var Name = 'Scott';
var job = 'Manager';
var permanent_emp = true;
var emp_salary = "INR.45000";
var dept_no = 10;
console.log("Employee ID: " + " " + Id);
console.log("Employee Name: " + " " + Name);
console.log("Employee Job: " + " " + job);
console.log("Is Permanent Employee: " + " " + permanent_emp);
console.log("Employee Salary: " + " " + emp_salary);
console.log("Employee Deptno: " + " " + dept_no);
